version: '3'

services:

    nginx:
     container_name: gol_nginx
     image: nginx:latest
     ports:
        - 80:80
     networks:
        - angular_net
     volumes:
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf

    angular:
     container_name: gol_angular
     build: ./angular
     networks:
        - angular_net
     volumes:
        - ./angular/:/app
     working_dir:
        /app


networks:
  angular_net:
    driver: bridge



